// ADD TO CART
export const ADD_TO_CART = 'CartProduct/ADD_TO_CART';
export const ADD_TO_CART_SUCCESS = 'CartProduct/ADD_TO_CART_SUCCESS';

// UPDATE CART
export const INCREASE_ITEM_QUANTITY = 'CartProduct/INCREASE_ITEM_QUANTITY';
export const DECREASE_ITEM_QUANTITY = 'CartProduct/DECREASE_ITEM_QUANTITY';
export const UPDATE_CART_ITEM_REQUEST = 'CartProduct/UPDATE_CART_ITEM_REQUEST';

// REMOVE FROM CART
export const REMOVE_FROM_CART_REQUEST = 'CartProduct/REMOVE_FROM_CART_REQUEST';
export const REMOVE_FROM_CART_SUCCESS = 'CartProduct/REMOVE_FROM_CART_SUCCESS';
export const REMOVE_FROM_CART_FAILURE = 'CartProduct/REMOVE_FROM_CART_FAILURE';

// MIDTRANS
export const MIDTRANS_REQUEST = 'CartProduct/MIDTRANS_REQUEST';
export const MIDTRANS_SUCCESS = 'CartProduct/MIDTRANS_SUCCESS';
