export const UPDATE_PRODUCT_REQUEST = 'UpdateProduct/UPDATE_PRODUCT_REQUEST';
export const FETCH_DATA_REQUEST = 'UpdateProduct/FETCH_DATA_REQUEST';
export const FETCH_DATA_SUCCESS = 'UpdateProduct/FETCH_DATA_SUCCESS';
