// GET PRODUCT
export const GET_PRODUCT_REQUEST = 'Home/GET_PRODUCT_REQUEST';
export const GET_PRODUCT_SUCCESS = 'Home/GET_PRODUCT_SUCCESS';
export const GET_PRODUCT_FAILURE = 'Home/GET_PRODUCT_FAILURE';

// GET PRODUCT BY ID
export const GET_PRODUCT_ID_REQUEST = 'Home/GET_PRODUCT_ID_REQUEST';
export const GET_PRODUCT_ID_SUCCESS = 'Home/GET_PRODUCT_ID_SUCCESS';
export const GET_PRODUCT_ID_FAILURE = 'Home/GET_PRODUCT_ID_FAILURE';

// CREATE PRODUCT
export const CREATE_PRODUCT_REQUEST = 'Home/CREATE_PRODUCT_REQUEST';
export const CREATE_PRODUCT_SUCCESS = 'Home/CREATE_PRODUCT_SUCCESS';
export const CREATE_PRODUCT_FAILURE = 'Home/CREATE_PRODUCT_FAILURE';

// DELETE PRODUCT
export const DELETE_PRODUCT_REQUEST = 'DELETE_PRODUCT_REQUEST';
export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS';
export const DELETE_PRODUCT_FAILURE = 'DELETE_PRODUCT_FAILURE';

// MIDTRANS
export const PAYMENT_REQUEST = 'Home/PAYMENT_REQUEST';
export const PAYMENT_SUCCESS = 'Home/PAYMENT_SUCCESS';
